2020-12-10 00:21:21.300 [error] <0.2272.0> CRASH REPORT Process <0.2272.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/..."},...]},...]},...},...},...}
2020-12-10 00:21:21.301 [error] <0.2272.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.2271.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/co..."},...]},...]},...},...}
2020-12-10 00:22:49.872 [error] <0.2286.0> CRASH REPORT Process <0.2286.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,25}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/..."},...]},...]},...},...},...}
2020-12-10 00:22:49.873 [error] <0.2286.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.2284.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,25}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/co..."},...]},...]},...},...}
