2020-12-09 16:06:21.124 [error] <0.1577.0> gen_server <0.1577.0> terminated with reason: {socket_error,timeout}
2020-12-09 16:06:21.128 [error] <0.1577.0> CRASH REPORT Process <0.1577.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 16:06:21.129 [error] <0.1573.0> gen_server <0.1573.0> terminated with reason: {socket_error,timeout}
2020-12-09 16:06:21.131 [error] <0.1572.0> Supervisor {<0.1572.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.1788>, <0.1573.0>, <0.1575.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:55496 -> 127.0.0.1:5672">>) at <0.1577.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 16:06:21.131 [error] <0.1572.0> Supervisor {<0.1572.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.1788>, <0.1573.0>, <0.1575.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:55496 -> 127.0.0.1:5672">>) at <0.1577.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 16:06:21.131 [error] <0.1573.0> CRASH REPORT Process <0.1573.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 16:06:21.132 [error] <0.1571.0> Supervisor {<0.1571.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1572.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1573.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 16:06:21.133 [error] <0.1571.0> Supervisor {<0.1571.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1572.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1573.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 16:56:08.563 [error] <0.556.0> Failed to start Ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2020-12-09 16:56:08.584 [error] <0.556.0> CRASH REPORT Process <0.556.0> with 0 neighbours exited with reason: {listen_error,'Elixir.GuardianWeb.Endpoint.HTTP',eaddrinuse} in ranch_acceptors_sup:listen_error/5 line 66
2020-12-09 16:56:08.584 [error] <0.554.0> Supervisor {<0.554.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.GuardianWeb.Endpoint.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.GuardianWeb.Endpoint.HTTP',eaddrinuse} in context start_error
2020-12-09 16:57:16.163 [error] <0.556.0> Failed to start Ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2020-12-09 16:57:16.175 [error] <0.556.0> CRASH REPORT Process <0.556.0> with 0 neighbours exited with reason: {listen_error,'Elixir.GuardianWeb.Endpoint.HTTP',eaddrinuse} in ranch_acceptors_sup:listen_error/5 line 66
2020-12-09 16:57:16.175 [error] <0.554.0> Supervisor {<0.554.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.GuardianWeb.Endpoint.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.GuardianWeb.Endpoint.HTTP',eaddrinuse} in context start_error
2020-12-09 18:00:18.031 [error] <0.1201.0> CRASH REPORT Process <0.1201.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,#{'__exception__' => true,'__struct__' => 'Elixir.HTTPoison.Error',id => nil,reason => econnrefused}}},[{'Elixir.Guardian.AssignationsReportAdmin',assignations_report,1,[{file,"lib/guardian/assignations_report_admin.ex"},{line,9}]},{'Elixir.GuardianWeb.Admin.AssignationsReportController',index,3,[{file,"lib/guardian_web/controllers/admin/assignations_report_controller.ex"},{line,13}]},{'Elixir.GuardianWeb.Admin.AssignationsReportController',...},...]},...},...},...}
2020-12-09 18:00:18.045 [error] <0.1201.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1199.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,#{'__exception__' => true,'__struct__' => 'Elixir.HTTPoison.Error',id => nil,reason => econnrefused}}},[{'Elixir.Guardian.AssignationsReportAdmin',assignations_report,1,[{file,"lib/guardian/assignations_report_admin.ex"},{line,9}]},{'Elixir.GuardianWeb.Admin.AssignationsReportController',index,3,[{file,"lib/guardian_web/controllers/admin/assignations_report_controller.ex"},{line,13}]},{'Elixir.GuardianWeb.Admin.AssignationsReportController',...},...]},...},...}
2020-12-09 18:01:51.576 [error] <0.1227.0> CRASH REPORT Process <0.1227.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,#{'__exception__' => true,'__struct__' => 'Elixir.HTTPoison.Error',id => nil,reason => econnrefused}}},[{'Elixir.Guardian.InvoicesAdmin',get_invoices,3,[{file,"lib/guardian/invoices_admin.ex"},{line,7}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,16}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guar..."},...]},...]},...},...},...}
2020-12-09 18:01:51.578 [error] <0.1227.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1215.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,#{'__exception__' => true,'__struct__' => 'Elixir.HTTPoison.Error',id => nil,reason => econnrefused}}},[{'Elixir.Guardian.InvoicesAdmin',get_invoices,3,[{file,"lib/guardian/invoices_admin.ex"},{line,7}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,16}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardi..."},...]},...]},...},...}
2020-12-09 19:16:25.292 [error] <0.726.0> CRASH REPORT Process <0.726.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardian_key=SFMyNTY.g3QAAAADbQAAAAtfY3NyZl90b2tlbm0...">>,...},...}},...},...},...},...},...},...}
2020-12-09 19:16:25.292 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardian_key=SFMyNTY.g3QAAAADbQAAAAtf...">>,...},...}},...},...},...},...},...},...}
2020-12-09 19:16:25.293 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guard...">>,...},...}},...},...},...},...},...},...}
2020-12-09 19:16:25.373 [error] <0.729.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.728.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardia...">>,...},...}},...},...},...},...},...}
2020-12-09 19:16:25.373 [error] <0.726.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.723.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardian_key=SFMyNTY.g3QAAAADbQAAAAtfY3NyZl90b2tlbm0AA...">>,...},...}},...},...},...},...},...}
2020-12-09 19:16:25.374 [error] <0.725.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.719.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardian_key=SFMyNTY.g3QAAAADbQAAAAtfY3...">>,...},...}},...},...},...},...},...}
2020-12-09 19:16:25.576 [error] <0.736.0> CRASH REPORT Process <0.736.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guard...">>,...},...}},...},...},...},...},...},...}
2020-12-09 19:16:25.576 [error] <0.736.0> Cowboy stream 2 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.728.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardia...">>,...},...}},...},...},...},...},...}
2020-12-09 19:16:34.133 [error] <0.760.0> CRASH REPORT Process <0.760.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardian_key=SFMyNTY.g3QAAAADbQAAAAtf...">>,...},...}},...},...},...},...},...},...}
2020-12-09 19:16:34.135 [error] <0.760.0> Cowboy stream 8 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.728.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardian_key=SFMyNTY.g3QAAAADbQAAAAtfY3...">>,...},...}},...},...},...},...},...}
2020-12-09 19:16:34.266 [error] <0.761.0> CRASH REPORT Process <0.761.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardian_key=SFMyNTY.g3QAAAADbQAAAAtfY3NyZl90b2tlbm0...">>,...},...}},...},...},...},...},...},...}
2020-12-09 19:16:34.267 [error] <0.761.0> Cowboy stream 4 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.719.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardian_key=SFMyNTY.g3QAAAADbQAAAAtfY3NyZl90b2tlbm0AA...">>,...},...}},...},...},...},...},...}
2020-12-09 19:16:34.403 [error] <0.763.0> CRASH REPORT Process <0.763.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guard...">>,...},...}},...},...},...},...},...},...}
2020-12-09 19:16:34.404 [error] <0.763.0> Cowboy stream 2 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.723.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"_guardia...">>,...},...}},...},...},...},...},...}
2020-12-09 20:47:19.222 [error] <0.1178.0> gen_server <0.1178.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.223 [error] <0.896.0> gen_server <0.896.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.223 [error] <0.892.0> gen_server <0.892.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.223 [error] <0.1092.0> gen_server <0.1092.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.223 [error] <0.1270.0> gen_server <0.1270.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.223 [error] <0.800.0> gen_server <0.800.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.224 [error] <0.1010.0> gen_server <0.1010.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.224 [error] <0.818.0> gen_server <0.818.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.224 [error] <0.1266.0> gen_server <0.1266.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.224 [error] <0.1174.0> gen_server <0.1174.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.224 [error] <0.1174.0> CRASH REPORT Process <0.1174.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 20:47:19.224 [error] <0.796.0> gen_server <0.796.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.224 [error] <0.1088.0> gen_server <0.1088.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.228 [error] <0.814.0> gen_server <0.814.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.230 [error] <0.1172.0> Supervisor {<0.1172.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1173.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1174.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 20:47:19.230 [error] <0.1006.0> gen_server <0.1006.0> terminated with reason: {socket_error,timeout}
2020-12-09 20:47:19.231 [error] <0.1172.0> Supervisor {<0.1172.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1173.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1174.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 20:47:19.232 [error] <0.1006.0> CRASH REPORT Process <0.1006.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 20:47:19.232 [error] <0.1088.0> CRASH REPORT Process <0.1088.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 20:47:19.233 [error] <0.814.0> CRASH REPORT Process <0.814.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 20:47:19.233 [error] <0.892.0> CRASH REPORT Process <0.892.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 20:47:19.234 [error] <0.1004.0> Supervisor {<0.1004.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1005.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1006.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 20:47:19.235 [error] <0.1004.0> Supervisor {<0.1004.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1005.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1006.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 20:47:19.235 [error] <0.1086.0> Supervisor {<0.1086.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1087.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1088.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 20:47:19.236 [error] <0.1086.0> Supervisor {<0.1086.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1087.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1088.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 20:47:19.241 [error] <0.812.0> Supervisor {<0.812.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.813.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.814.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 20:47:19.242 [error] <0.812.0> Supervisor {<0.812.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.813.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.814.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 20:47:19.242 [error] <0.1266.0> CRASH REPORT Process <0.1266.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 20:47:19.242 [error] <0.796.0> CRASH REPORT Process <0.796.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 20:47:19.244 [error] <0.890.0> Supervisor {<0.890.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.891.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.892.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 20:47:19.244 [error] <0.890.0> Supervisor {<0.890.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.891.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.892.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 20:47:19.244 [error] <0.794.0> Supervisor {<0.794.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.795.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.796.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 20:47:19.245 [error] <0.794.0> Supervisor {<0.794.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.795.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.796.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 20:47:19.245 [error] <0.1264.0> Supervisor {<0.1264.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1265.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1266.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 20:47:19.245 [error] <0.1264.0> Supervisor {<0.1264.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1265.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.1266.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 22:12:46.255 [error] <0.993.0> gen_server <0.993.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.269 [error] <0.763.0> gen_server <0.763.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.269 [error] <0.929.0> gen_server <0.929.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.270 [error] <0.925.0> gen_server <0.925.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.273 [error] <0.800.0> gen_server <0.800.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.273 [error] <0.759.0> gen_server <0.759.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.273 [error] <0.989.0> gen_server <0.989.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.274 [error] <0.959.0> gen_server <0.959.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.274 [error] <0.955.0> gen_server <0.955.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.278 [error] <0.796.0> gen_server <0.796.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:46.280 [error] <0.925.0> CRASH REPORT Process <0.925.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 22:12:46.280 [error] <0.989.0> CRASH REPORT Process <0.989.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 22:12:46.280 [error] <0.759.0> CRASH REPORT Process <0.759.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 22:12:46.281 [error] <0.796.0> CRASH REPORT Process <0.796.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 22:12:46.281 [error] <0.757.0> Supervisor {<0.757.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.758.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.759.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 22:12:46.281 [error] <0.757.0> Supervisor {<0.757.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.758.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.759.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 22:12:46.282 [error] <0.955.0> CRASH REPORT Process <0.955.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 22:12:46.282 [error] <0.923.0> Supervisor {<0.923.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.924.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.925.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 22:12:46.282 [error] <0.923.0> Supervisor {<0.923.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.924.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.925.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 22:12:46.282 [error] <0.987.0> Supervisor {<0.987.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.988.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.989.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 22:12:46.283 [error] <0.987.0> Supervisor {<0.987.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.988.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.989.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 22:12:46.283 [error] <0.794.0> Supervisor {<0.794.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.795.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.796.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 22:12:46.283 [error] <0.794.0> Supervisor {<0.794.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.795.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.796.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 22:12:46.284 [error] <0.953.0> Supervisor {<0.953.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.954.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.955.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 22:12:46.284 [error] <0.953.0> Supervisor {<0.953.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.954.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.955.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 22:12:46.631 [error] <0.896.0> gen_server <0.896.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:47.435 [error] <0.896.0> CRASH REPORT Process <0.896.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 22:12:47.435 [error] <0.892.0> gen_server <0.892.0> terminated with reason: {socket_error,timeout}
2020-12-09 22:12:47.435 [error] <0.891.0> Supervisor {<0.891.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.136>, <0.892.0>, <0.894.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:55109 -> 127.0.0.1:5672">>) at <0.896.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 22:12:47.435 [error] <0.891.0> Supervisor {<0.891.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.136>, <0.892.0>, <0.894.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:55109 -> 127.0.0.1:5672">>) at <0.896.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 22:12:47.435 [error] <0.892.0> CRASH REPORT Process <0.892.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-12-09 22:12:47.436 [error] <0.890.0> Supervisor {<0.890.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.891.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.892.0> exit with reason {socket_error,timeout} in context child_terminated
2020-12-09 22:12:47.436 [error] <0.890.0> Supervisor {<0.890.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.891.0>, {amqp_params_network,<<"user">>,{plaintext,<<"password">>},<<"/">>,"localhost",5672,0,0,10,50000,...}) at <0.892.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-09 22:49:50.909 [error] <0.1171.0> CRASH REPORT Process <0.1171.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:50.910 [error] <0.1173.0> CRASH REPORT Process <0.1173.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SF...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:50.935 [error] <0.1173.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1167.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SFMy...">>,...},...}},...},...},...},...},...}
2020-12-09 22:49:50.936 [error] <0.1171.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1165.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _gu...">>,...},...}},...},...},...},...},...}
2020-12-09 22:49:50.952 [error] <0.1176.0> CRASH REPORT Process <0.1176.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:50.953 [error] <0.1176.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1175.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:d...">>,...},...}},...},...},...},...},...}
2020-12-09 22:49:53.830 [error] <0.1187.0> CRASH REPORT Process <0.1187.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:53.831 [error] <0.1187.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1175.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _gu...">>,...},...}},...},...},...},...},...}
2020-12-09 22:49:53.885 [error] <0.1189.0> CRASH REPORT Process <0.1189.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:53.886 [error] <0.1189.0> Cowboy stream 4 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1165.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:d...">>,...},...}},...},...},...},...},...}
2020-12-09 22:49:53.894 [error] <0.1186.0> CRASH REPORT Process <0.1186.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SF...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:53.895 [error] <0.1186.0> Cowboy stream 2 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1167.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SFMy...">>,...},...}},...},...},...},...},...}
2020-12-09 22:49:56.737 [error] <0.1197.0> CRASH REPORT Process <0.1197.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:56.739 [error] <0.1197.0> Cowboy stream 4 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1167.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=...">>,...},...}},...},...},...},...},...}
2020-12-09 22:49:56.793 [error] <0.1198.0> CRASH REPORT Process <0.1198.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpw...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:56.793 [error] <0.1198.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1165.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYX...">>,...},...}},...},...},...},...},...}
2020-12-09 22:49:56.866 [error] <0.1200.0> CRASH REPORT Process <0.1200.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"k...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:56.866 [error] <0.1200.0> Cowboy stream 4 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1175.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"kee...">>,...},...}},...},...},...},...},...}
2020-12-09 22:49:56.956 [error] <0.1206.0> CRASH REPORT Process <0.1206.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"k...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:49:56.956 [error] <0.1206.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1175.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"kee...">>,...},...}},...},...},...},...},...}
2020-12-09 22:50:59.611 [error] <0.666.0> CRASH REPORT Process <0.666.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:50:59.663 [error] <0.666.0> Cowboy stream 2 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.662.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _gu...">>,...},...}},...},...},...},...},...}
2020-12-09 22:50:59.790 [error] <0.667.0> CRASH REPORT Process <0.667.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SF...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:50:59.792 [error] <0.667.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.663.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SFMy...">>,...},...}},...},...},...},...},...}
2020-12-09 22:50:59.857 [error] <0.670.0> CRASH REPORT Process <0.670.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:50:59.858 [error] <0.670.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.669.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:d...">>,...},...}},...},...},...},...},...}
2020-12-09 22:51:04.445 [error] <0.682.0> CRASH REPORT Process <0.682.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:51:04.447 [error] <0.682.0> Cowboy stream 4 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.669.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _gu...">>,...},...}},...},...},...},...},...}
2020-12-09 22:51:04.873 [error] <0.684.0> CRASH REPORT Process <0.684.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SF...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:51:04.874 [error] <0.684.0> Cowboy stream 2 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.663.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SFMy...">>,...},...}},...},...},...},...},...}
2020-12-09 22:51:05.264 [error] <0.685.0> CRASH REPORT Process <0.685.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:51:05.266 [error] <0.685.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.662.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:d...">>,...},...}},...},...},...},...},...}
2020-12-09 22:51:10.126 [error] <0.693.0> CRASH REPORT Process <0.693.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:51:10.127 [error] <0.693.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.662.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _gu...">>,...},...}},...},...},...},...},...}
2020-12-09 22:51:10.190 [error] <0.694.0> CRASH REPORT Process <0.694.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SF...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:51:10.195 [error] <0.694.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.663.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SFMy...">>,...},...}},...},...},...},...},...}
2020-12-09 22:51:10.344 [error] <0.696.0> CRASH REPORT Process <0.696.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:51:10.356 [error] <0.696.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.669.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:d...">>,...},...}},...},...},...},...},...}
2020-12-09 22:51:17.418 [error] <0.704.0> CRASH REPORT Process <0.704.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:51:17.422 [error] <0.704.0> Cowboy stream 7 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.669.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _gu...">>,...},...}},...},...},...},...},...}
2020-12-09 22:51:17.450 [error] <0.705.0> CRASH REPORT Process <0.705.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SF...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:51:17.451 [error] <0.705.0> Cowboy stream 4 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.663.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SFMy...">>,...},...}},...},...},...},...},...}
2020-12-09 22:51:17.615 [error] <0.707.0> CRASH REPORT Process <0.707.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:51:17.619 [error] <0.707.0> Cowboy stream 6 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.662.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:d...">>,...},...}},...},...},...},...},...}
2020-12-09 22:53:37.272 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:53:37.272 [error] <0.666.0> CRASH REPORT Process <0.666.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SF...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:53:37.278 [error] <0.665.0> CRASH REPORT Process <0.665.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _...">>,...},...}},...},...},...},...},...},...}
2020-12-09 22:53:37.328 [error] <0.665.0> Cowboy stream 2 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.662.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _gu...">>,...},...}},...},...},...},...},...}
2020-12-09 22:53:37.329 [error] <0.666.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.661.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:dXNlcjpwYXNzd29yZA%253D%253D; _guardian_key=SFMy...">>,...},...}},...},...},...},...},...}
2020-12-09 22:53:37.337 [error] <0.669.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.668.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-419,es;q=0.9,en;q=0.8">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"m=2258:d...">>,...},...}},...},...},...},...},...}
