2020-12-10 00:21:21.300 [error] <0.2272.0> CRASH REPORT Process <0.2272.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/..."},...]},...]},...},...},...}
2020-12-10 00:21:21.301 [error] <0.2272.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.2271.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/co..."},...]},...]},...},...}
2020-12-10 00:22:49.872 [error] <0.2286.0> CRASH REPORT Process <0.2286.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,25}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/..."},...]},...]},...},...},...}
2020-12-10 00:22:49.873 [error] <0.2286.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.2284.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,25}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/co..."},...]},...]},...},...}
2020-12-10 01:53:43.688 [error] <0.3841.0> CRASH REPORT Process <0.3841.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => create,message => nil,module => 'Elixir.GuardianWeb.Admin.NotificationConfigController',reason => nil},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',create,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 146,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"text/html,applicati...">>,...},...}},...},...],...},...]},...},...},...}
2020-12-10 01:53:43.708 [error] <0.3841.0> Cowboy stream 7 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.3503.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => create,message => nil,module => 'Elixir.GuardianWeb.Admin.NotificationConfigController',reason => nil},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',create,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 146,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"text/html,application...">>,...},...}},...},...],...},...]},...},...}
2020-12-10 02:02:20.050 [error] <0.4134.0> CRASH REPORT Process <0.4134.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity">> => <<"3">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...},...}
2020-12-10 02:02:20.058 [error] <0.4134.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.3963.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity">> => <<"3">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...}
2020-12-10 02:02:47.547 [error] <0.4143.0> CRASH REPORT Process <0.4143.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity">> => <<"3">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...},...}
2020-12-10 02:02:47.549 [error] <0.4143.0> Cowboy stream 7 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.3963.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity">> => <<"3">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...}
2020-12-10 02:02:58.127 [error] <0.4188.0> CRASH REPORT Process <0.4188.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity_filter">> => <<"1">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...},...}
2020-12-10 02:02:58.128 [error] <0.4188.0> Cowboy stream 7 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.4145.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity_filter">> => <<"1">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...}
2020-12-10 02:15:43.862 [error] <0.4477.0> CRASH REPORT Process <0.4477.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => get_invoices,message => nil,module => 'Elixir.Guardian.NotificationConfigAdmin',reason => nil},[{'Elixir.Guardian.NotificationConfigAdmin',get_invoices,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Guardian.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Guardian.Accounts.User',confirmed_at => #{...},...}],...},...]},...},...},...}
2020-12-10 02:15:43.862 [error] <0.4477.0> Cowboy stream 6 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.4295.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => get_invoices,message => nil,module => 'Elixir.Guardian.NotificationConfigAdmin',reason => nil},[{'Elixir.Guardian.NotificationConfigAdmin',get_invoices,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Guardian.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Guardian.Accounts.User',confirmed_at => #{...},...}],...},...]},...},...}
2020-12-10 02:16:20.421 [error] <0.4568.0> CRASH REPORT Process <0.4568.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvico/Documents/Projects/facultad/asp/guardian/billing/app.js:33:8<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/juanvico/Documents/Projects/facultad/asp/guardian/billing/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;...">>,...},...},...},...},...}
2020-12-10 02:16:20.422 [error] <0.4568.0> Cowboy stream 9 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.4296.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvico/Documents/Projects/facultad/asp/guardian/billing/app.js:33:8<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/juanvico/Documents/Projects/facultad/asp/guardian/billing/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at...">>,...},...},...},...}
2020-12-10 02:24:37.091 [error] <0.4780.0> CRASH REPORT Process <0.4780.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => fetch,message => nil,module => 'Elixir.HTTPoison.Response',reason => <<"HTTPoison.Response does not implement the Access behaviour">>},[{'Elixir.HTTPoison.Response',fetch,[#{'__struct__' => 'Elixir.HTTPoison.Response',body => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvi...">>,...},...],...},...]},...},...},...}
2020-12-10 02:24:37.093 [error] <0.4780.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.4778.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => fetch,message => nil,module => 'Elixir.HTTPoison.Response',reason => <<"HTTPoison.Response does not implement the Access behaviour">>},[{'Elixir.HTTPoison.Response',fetch,[#{'__struct__' => 'Elixir.HTTPoison.Response',body => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvico...">>,...},...],...},...]},...},...}
2020-12-10 02:36:48.400 [error] <0.5091.0> CRASH REPORT Process <0.5091.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @error not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:config, :conn, :current_user, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,134}]},...]},...},...},...}
2020-12-10 02:36:48.406 [error] <0.5091.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.5090.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @error not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:config, :conn, :current_user, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,134}]},...]},...},...}
2020-12-10 03:39:00.697 [error] <0.6149.0> CRASH REPORT Process <0.6149.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @errors not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:by_severity, :conn, :current_user, :resolved, :top_developers, :total_errors, :unassigned_errors, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine',...},...]},...},...},...}
2020-12-10 03:39:00.697 [error] <0.6149.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6073.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @errors not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:by_severity, :conn, :current_user, :resolved, :top_developers, :total_errors, :unassigned_errors, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine',...},...]},...},...}
2020-12-10 03:40:10.806 [error] <0.6229.0> CRASH REPORT Process <0.6229.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 3,function => get_statistics_report,message => nil,module => 'Elixir.Guardian.StatisticsAdmin',reason => nil},[{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Guardian.Accounts.Organization',source => <<"organizations">>,state => loaded},'__struct__' => 'Elixir.Guardian.Accounts.Organization',...},...],...},...]},...},...},...}
2020-12-10 03:40:10.807 [error] <0.6229.0> Cowboy stream 12 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6157.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 3,function => get_statistics_report,message => nil,module => 'Elixir.Guardian.StatisticsAdmin',reason => nil},[{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Guardian.Accounts.Organization',source => <<"organizations">>,state => loaded},'__struct__' => 'Elixir.Guardian.Accounts.Organization',...},...],...},...]},...},...}
2020-12-10 03:41:02.654 [error] <0.6239.0> CRASH REPORT Process <0.6239.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:41:02.657 [error] <0.6239.0> Cowboy stream 14 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6157.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:41:16.716 [error] <0.6312.0> CRASH REPORT Process <0.6312.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:41:16.718 [error] <0.6312.0> Cowboy stream 18 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6157.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:42:20.771 [error] <0.6386.0> CRASH REPORT Process <0.6386.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,26}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:42:20.774 [error] <0.6386.0> Cowboy stream 22 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6157.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,26}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:46:12.283 [error] <0.6490.0> CRASH REPORT Process <0.6490.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,26}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:46:12.294 [error] <0.6490.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6424.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,26}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:46:59.250 [error] <0.6565.0> CRASH REPORT Process <0.6565.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:46:59.257 [error] <0.6565.0> Cowboy stream 7 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6424.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:47:49.489 [error] <0.6639.0> CRASH REPORT Process <0.6639.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:47:49.490 [error] <0.6639.0> Cowboy stream 11 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6424.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:48:22.613 [error] <0.6652.0> CRASH REPORT Process <0.6652.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:48:22.614 [error] <0.6652.0> Cowboy stream 13 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6424.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:49:51.511 [error] <0.6729.0> CRASH REPORT Process <0.6729.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:49:51.511 [error] <0.6729.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6662.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:53:08.759 [error] <0.6846.0> CRASH REPORT Process <0.6846.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => from_iso8601,kind => nil,module => 'Elixir.Date'},[{'Elixir.Date',from_iso8601,[#{'__struct__' => 'Elixir.Date',calendar => 'Elixir.Calendar.ISO',day => 3,month => 10,year => 2020},'Elixir.Calendar.ISO'],[{file,"lib/calendar/date.ex"},{line,268}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report_info,3,[{file,"lib/guardian/statistics_admin.ex"},{line,40}]},{...},...]},...},...},...}
2020-12-10 03:53:08.759 [error] <0.6846.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6741.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => from_iso8601,kind => nil,module => 'Elixir.Date'},[{'Elixir.Date',from_iso8601,[#{'__struct__' => 'Elixir.Date',calendar => 'Elixir.Calendar.ISO',day => 3,month => 10,year => 2020},'Elixir.Calendar.ISO'],[{file,"lib/calendar/date.ex"},{line,268}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report_info,3,[{file,"lib/guardian/statistics_admin.ex"},{line,40}]},{'Elixir.Guardian.StatisticsAdmin',...},...]},...},...}
2020-12-10 03:56:52.391 [error] <0.6861.0> CRASH REPORT Process <0.6861.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => <<"2020-10-03">>},[{'Elixir.Guardian.StatisticsAdmin',get_statistics_report_info,3,[{file,"lib/guardian/statistics_admin.ex"},{line,40}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,8}]},{'Elixir.GuardianWeb.Admin.StatisticsController',index,3,[{file,"lib/guardian_web/controllers/admin/statistics_controller.ex"},{line,17}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:56:52.393 [error] <0.6861.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6859.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => <<"2020-10-03">>},[{'Elixir.Guardian.StatisticsAdmin',get_statistics_report_info,3,[{file,"lib/guardian/statistics_admin.ex"},{line,40}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,8}]},{'Elixir.GuardianWeb.Admin.StatisticsController',index,3,[{file,"lib/guardian_web/controllers/admin/statistics_controller.ex"},{line,17}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:57:11.064 [error] <0.6934.0> CRASH REPORT Process <0.6934.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => <<"2020-10-04">>},[{'Elixir.Guardian.StatisticsAdmin',get_statistics_report_info,3,[{file,"lib/guardian/statistics_admin.ex"},{line,40}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,8}]},{'Elixir.GuardianWeb.Admin.StatisticsController',index,3,[{file,"lib/guardian_web/controllers/admin/statistics_controller.ex"},{line,17}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:57:11.064 [error] <0.6934.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6859.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => <<"2020-10-04">>},[{'Elixir.Guardian.StatisticsAdmin',get_statistics_report_info,3,[{file,"lib/guardian/statistics_admin.ex"},{line,40}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,8}]},{'Elixir.GuardianWeb.Admin.StatisticsController',index,3,[{file,"lib/guardian_web/controllers/admin/statistics_controller.ex"},{line,17}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:58:30.124 [error] <0.6945.0> CRASH REPORT Process <0.6945.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:58:30.124 [error] <0.6945.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6943.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:58:55.779 [error] <0.7011.0> CRASH REPORT Process <0.7011.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:58:55.782 [error] <0.7011.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6943.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 03:59:47.549 [error] <0.7020.0> CRASH REPORT Process <0.7020.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 03:59:47.550 [error] <0.7020.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6943.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 04:00:35.782 [error] <0.7030.0> CRASH REPORT Process <0.7030.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 04:00:35.785 [error] <0.7030.0> Cowboy stream 7 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.6943.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,27}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 04:04:34.291 [error] <0.7045.0> CRASH REPORT Process <0.7045.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => '-total_errors_for_severity/2-fun-0-',kind => nil,module => 'Elixir.GuardianWeb.Admin.StatisticsView'},[{'Elixir.GuardianWeb.Admin.StatisticsView','-total_errors_for_severity/2-fun-0-',[#{<<"_id">> => 4,<<"count">> => 5}],[{file,"lib/guardian_web/views/admin/statistics_view.ex"},{line,9}]},{'Elixir.Enum',find_list,3,[{file,"lib/enum.ex"},{line,2956}]},{'Elixir.GuardianWeb.Admin.StatisticsView',...},...]},...},...},...}
2020-12-10 04:04:34.292 [error] <0.7045.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.7043.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => '-total_errors_for_severity/2-fun-0-',kind => nil,module => 'Elixir.GuardianWeb.Admin.StatisticsView'},[{'Elixir.GuardianWeb.Admin.StatisticsView','-total_errors_for_severity/2-fun-0-',[#{<<"_id">> => 4,<<"count">> => 5}],[{file,"lib/guardian_web/views/admin/statistics_view.ex"},{line,9}]},{'Elixir.Enum',find_list,3,[{file,"lib/enum.ex"},{line,2956}]},{'Elixir.GuardianWeb.Admin.StatisticsView',...},...]},...},...}
2020-12-10 04:05:45.435 [error] <0.7112.0> CRASH REPORT Process <0.7112.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => '-total_errors_for_severity/2-fun-0-',kind => nil,module => 'Elixir.GuardianWeb.Admin.StatisticsView'},[{'Elixir.GuardianWeb.Admin.StatisticsView','-total_errors_for_severity/2-fun-0-',[#{<<"_id">> => 4,<<"count">> => 5}],[{file,"lib/guardian_web/views/admin/statistics_view.ex"},{line,9}]},{'Elixir.Enum',find_list,3,[{file,"lib/enum.ex"},{line,2956}]},{'Elixir.GuardianWeb.Admin.StatisticsView',...},...]},...},...},...}
2020-12-10 04:05:45.435 [error] <0.7112.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.7110.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => '-total_errors_for_severity/2-fun-0-',kind => nil,module => 'Elixir.GuardianWeb.Admin.StatisticsView'},[{'Elixir.GuardianWeb.Admin.StatisticsView','-total_errors_for_severity/2-fun-0-',[#{<<"_id">> => 4,<<"count">> => 5}],[{file,"lib/guardian_web/views/admin/statistics_view.ex"},{line,9}]},{'Elixir.Enum',find_list,3,[{file,"lib/enum.ex"},{line,2956}]},{'Elixir.GuardianWeb.Admin.StatisticsView',...},...]},...},...}
2020-12-10 04:05:48.418 [error] <0.7133.0> CRASH REPORT Process <0.7133.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => '-total_errors_for_severity/2-fun-0-',kind => nil,module => 'Elixir.GuardianWeb.Admin.StatisticsView'},[{'Elixir.GuardianWeb.Admin.StatisticsView','-total_errors_for_severity/2-fun-0-',[#{<<"_id">> => 4,<<"count">> => 5}],[{file,"lib/guardian_web/views/admin/statistics_view.ex"},{line,9}]},{'Elixir.Enum',find_list,3,[{file,"lib/enum.ex"},{line,2956}]},{'Elixir.GuardianWeb.Admin.StatisticsView',...},...]},...},...},...}
2020-12-10 04:05:48.436 [error] <0.7133.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.7111.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => '-total_errors_for_severity/2-fun-0-',kind => nil,module => 'Elixir.GuardianWeb.Admin.StatisticsView'},[{'Elixir.GuardianWeb.Admin.StatisticsView','-total_errors_for_severity/2-fun-0-',[#{<<"_id">> => 4,<<"count">> => 5}],[{file,"lib/guardian_web/views/admin/statistics_view.ex"},{line,9}]},{'Elixir.Enum',find_list,3,[{file,"lib/enum.ex"},{line,2956}]},{'Elixir.GuardianWeb.Admin.StatisticsView',...},...]},...},...}
2020-12-10 04:19:08.539 [error] <0.7499.0> CRASH REPORT Process <0.7499.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,'++',[#{},[<<"11">>]],[]},{'Elixir.Guardian.StatisticsAdmin','-get_statistics_report/3-fun-0-',2,[{file,"lib/guardian/statistics_admin.ex"},{line,14}]},{'Elixir.Enum','-each/2-lists^foreach/1-0-',2,[{file,"lib/enum.ex"},{line,783}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,783}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_..."},...]},...]},...},...},...}
2020-12-10 04:19:08.541 [error] <0.7499.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.7497.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,'++',[#{},[<<"11">>]],[]},{'Elixir.Guardian.StatisticsAdmin','-get_statistics_report/3-fun-0-',2,[{file,"lib/guardian/statistics_admin.ex"},{line,14}]},{'Elixir.Enum','-each/2-lists^foreach/1-0-',2,[{file,"lib/enum.ex"},{line,783}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,783}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_ad..."},...]},...]},...},...}
2020-12-10 04:58:06.228 [error] <0.5524.0> gen_server <0.5524.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.230 [error] <0.813.0> gen_server <0.813.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.245 [error] <0.2115.0> gen_server <0.2115.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.245 [error] <0.3466.0> gen_server <0.3466.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.245 [error] <0.3311.0> gen_server <0.3311.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.245 [error] <0.911.0> gen_server <0.911.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.248 [error] <0.3298.0> gen_server <0.3298.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.248 [error] <0.2128.0> gen_server <0.2128.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.249 [error] <0.5377.0> gen_server <0.5377.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.249 [error] <0.2145.0> gen_server <0.2145.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.249 [error] <0.843.0> gen_server <0.843.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.256 [error] <0.3219.0> gen_server <0.3219.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.256 [error] <0.745.0> gen_server <0.745.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.256 [error] <0.2177.0> gen_server <0.2177.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.256 [error] <0.4266.0> gen_server <0.4266.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.2206.0> gen_server <0.2206.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.873.0> gen_server <0.873.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.2085.0> gen_server <0.2085.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.3171.0> gen_server <0.3171.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.2190.0> gen_server <0.2190.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.5233.0> gen_server <0.5233.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.5641.0> gen_server <0.5641.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.2072.0> gen_server <0.2072.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.3247.0> gen_server <0.3247.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.5494.0> gen_server <0.5494.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.800.0> gen_server <0.800.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.257 [error] <0.3184.0> gen_server <0.3184.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.809.0> gen_server <0.809.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.5520.0> gen_server <0.5520.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.732.0> gen_server <0.732.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.771.0> gen_server <0.771.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.2219.0> gen_server <0.2219.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.5152.0> gen_server <0.5152.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.2158.0> gen_server <0.2158.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.2237.0> gen_server <0.2237.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.2250.0> gen_server <0.2250.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.258 [error] <0.784.0> gen_server <0.784.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.259 [error] <0.5687.0> gen_server <0.5687.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.259 [error] <0.2111.0> gen_server <0.2111.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.259 [error] <0.3462.0> gen_server <0.3462.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.259 [error] <0.5373.0> gen_server <0.5373.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.262 [error] <0.3307.0> gen_server <0.3307.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.275 [error] <0.907.0> gen_server <0.907.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.276 [error] <0.741.0> gen_server <0.741.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.276 [error] <0.5637.0> gen_server <0.5637.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.276 [error] <0.767.0> gen_server <0.767.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.276 [error] <0.2141.0> gen_server <0.2141.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.276 [error] <0.5682.0> gen_server <0.5682.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.276 [error] <0.3294.0> gen_server <0.3294.0> terminated with reason: {socket_error,timeout}
2020-12-10 04:58:06.279 [error] <0.2124.0> gen_server <0.2124.0> terminated with reason: {socket_error,timeout}
2020-12-10 09:27:46.195 [error] <0.7908.0> CRASH REPORT Process <0.7908.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,39}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...},...}
2020-12-10 09:27:46.198 [error] <0.7908.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.7882.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"the given module does not exist">>,protocol => 'Elixir.Ecto.Queryable',value => 'Elixir.User'},[{'Elixir.Ecto.Queryable.Atom',to_query,1,[{file,"lib/ecto/queryable.ex"},{line,40}]},{'Elixir.Ecto.Query.Builder.Filter',apply,3,[{file,"lib/ecto/query/builder/filter.ex"},{line,96}]},{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,39}]},{'Elixir.GuardianWeb.Admin.StatisticsController',...},...]},...},...}
2020-12-10 09:30:17.988 [error] <0.8088.0> CRASH REPORT Process <0.8088.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvico/Documents/Projects/facultad/asp/guardian/notifications/app.js:33:8<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/juanvico/Documents/Projects/facultad/asp/guardian/notifications/node_modules/express/lib/router/layer.js:95:5)<br> &...">>,...},...},...},...},...}
2020-12-10 09:30:17.989 [error] <0.8088.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.8044.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvico/Documents/Projects/facultad/asp/guardian/notifications/app.js:33:8<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/juanvico/Documents/Projects/facultad/asp/guardian/notifications/node_modules/express/lib/router/layer.js:95:5)<br> &nb...">>,...},...},...},...}
2020-12-10 09:42:56.292 [error] <0.8565.0> CRASH REPORT Process <0.8565.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,#{'__exception__' => true,'__struct__' => 'Elixir.HTTPoison.Error',id => nil,reason => econnrefused}}},[{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,9}]},{'Elixir.GuardianWeb.Admin.StatisticsController',index,3,[{file,"lib/guardian_web/controllers/admin/statistics_controller.ex"},{line,17}]},{'Elixir.GuardianWeb.Admin.StatisticsController',action,...},...]},...},...},...}
2020-12-10 09:42:56.293 [error] <0.8565.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.8563.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,#{'__exception__' => true,'__struct__' => 'Elixir.HTTPoison.Error',id => nil,reason => econnrefused}}},[{'Elixir.Guardian.StatisticsAdmin',get_statistics_report,3,[{file,"lib/guardian/statistics_admin.ex"},{line,9}]},{'Elixir.GuardianWeb.Admin.StatisticsController',index,3,[{file,"lib/guardian_web/controllers/admin/statistics_controller.ex"},{line,17}]},{'Elixir.GuardianWeb.Admin.StatisticsController',action,2,...},...]},...},...}
2020-12-10 09:54:42.528 [error] <0.8985.0> CRASH REPORT Process <0.8985.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @error not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:by_severity, :conn, :current_user, :resolved, :top_developers, :total_errors, :unassigned_errors, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine',...},...]},...},...},...}
2020-12-10 09:54:42.529 [error] <0.8985.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.8918.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @error not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:by_severity, :conn, :current_user, :resolved, :top_developers, :total_errors, :unassigned_errors, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine',...},...]},...},...}
2020-12-10 12:55:02.869 [error] <0.674.0> CRASH REPORT Process <0.674.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", passwo...">>},...},...},...},...}
2020-12-10 12:55:02.908 [error] <0.674.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.673.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", password...">>},...},...},...}
2020-12-10 12:57:29.627 [error] <0.807.0> CRASH REPORT Process <0.807.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", passwo...">>},...},...},...},...}
2020-12-10 12:57:29.639 [error] <0.807.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.806.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", password...">>},...},...},...}
2020-12-10 13:16:15.502 [error] <0.914.0> CRASH REPORT Process <0.914.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 63,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"application-key">> => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTYwMzE2NTAzMCwiaWF0IjoxNjAzMTU3ODMwLCJpc3MiOiJKb2tlbiIsImp0aSI6IjJvd...">>,...},...}},...},...],...},...},...},...},...}
2020-12-10 13:16:15.504 [error] <0.914.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.913.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 63,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"application-key">> => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTYwMzE2NTAzMCwiaWF0IjoxNjAzMTU3ODMwLCJpc3MiOiJKb2tlbiIsImp0aSI6IjJvdm9...">>,...},...}},...},...],...},...},...},...}
2020-12-10 13:18:01.354 [error] <0.936.0> CRASH REPORT Process <0.936.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.WithClauseError',term => []},[{'Elixir.GuardianWeb.Plugs.EnsureApiApplicationAuthenticated',call,2,[{file,"lib/guardian_web/plugs/ensure_api_application_authenticated.ex"},{line,9}]},{'Elixir.GuardianWeb.Router',ensure_api_application_authenticated,2,[]},{'Elixir.GuardianWeb.Router','__pipe_through2__',1,[{file,"lib/guardian_web/router.ex"},{line,1}]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,347}]},{'Elixir.GuardianWeb.Endpoint',...},...]},...},...},...}
2020-12-10 13:18:01.356 [error] <0.936.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.935.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.WithClauseError',term => []},[{'Elixir.GuardianWeb.Plugs.EnsureApiApplicationAuthenticated',call,2,[{file,"lib/guardian_web/plugs/ensure_api_application_authenticated.ex"},{line,9}]},{'Elixir.GuardianWeb.Router',ensure_api_application_authenticated,2,[]},{'Elixir.GuardianWeb.Router','__pipe_through2__',1,[{file,"lib/guardian_web/router.ex"},{line,1}]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,347}]},{'Elixir.GuardianWeb.Endpoint',...},...]},...},...}
2020-12-10 13:18:24.261 [error] <0.954.0> CRASH REPORT Process <0.954.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.WithClauseError',term => []},[{'Elixir.GuardianWeb.Plugs.EnsureApiApplicationAuthenticated',call,2,[{file,"lib/guardian_web/plugs/ensure_api_application_authenticated.ex"},{line,9}]},{'Elixir.GuardianWeb.Router',ensure_api_application_authenticated,2,[]},{'Elixir.GuardianWeb.Router','__pipe_through2__',1,[{file,"lib/guardian_web/router.ex"},{line,1}]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,347}]},{'Elixir.GuardianWeb.Endpoint',...},...]},...},...},...}
2020-12-10 13:18:24.263 [error] <0.954.0> Cowboy stream 2 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.935.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.WithClauseError',term => []},[{'Elixir.GuardianWeb.Plugs.EnsureApiApplicationAuthenticated',call,2,[{file,"lib/guardian_web/plugs/ensure_api_application_authenticated.ex"},{line,9}]},{'Elixir.GuardianWeb.Router',ensure_api_application_authenticated,2,[]},{'Elixir.GuardianWeb.Router','__pipe_through2__',1,[{file,"lib/guardian_web/router.ex"},{line,1}]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,347}]},{'Elixir.GuardianWeb.Endpoint',...},...]},...},...}
2020-12-10 13:19:16.915 [error] <0.1020.0> CRASH REPORT Process <0.1020.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 98,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"application-key">> => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTYwMzE2NTAzMCwiaWF0IjoxNjAzMTU3ODMwLCJpc3MiOiJKb2...">>,...},...}},...},...],...},...},...},...},...}
2020-12-10 13:19:16.916 [error] <0.1020.0> Cowboy stream 3 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.935.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 98,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"application-key">> => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTYwMzE2NTAzMCwiaWF0IjoxNjAzMTU3ODMwLCJpc3MiOiJKb2tl...">>,...},...}},...},...],...},...},...},...}
2020-12-10 13:19:39.218 [error] <0.1037.0> CRASH REPORT Process <0.1037.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 96,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"application-key">> => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTYwMzE2NTAzMCwiaWF0IjoxNjAzMTU3ODMwLCJpc3MiOiJKb2...">>,...},...}},...},...],...},...},...},...},...}
2020-12-10 13:19:39.231 [error] <0.1037.0> Cowboy stream 4 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.935.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 96,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"application-key">> => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTYwMzE2NTAzMCwiaWF0IjoxNjAzMTU3ODMwLCJpc3MiOiJKb2tl...">>,...},...}},...},...],...},...},...},...}
2020-12-10 13:19:49.205 [error] <0.1040.0> CRASH REPORT Process <0.1040.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 63,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"application-key">> => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTYwMzE2NTAzMCwiaWF0IjoxNjAzMTU3ODMwLCJpc3MiOiJKb2...">>,...},...}},...},...],...},...},...},...},...}
2020-12-10 13:19:49.209 [error] <0.1040.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.935.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 63,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"application-key">> => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTYwMzE2NTAzMCwiaWF0IjoxNjAzMTU3ODMwLCJpc3MiOiJKb2tl...">>,...},...}},...},...],...},...},...},...}
2020-12-10 13:20:44.411 [error] <0.1052.0> CRASH REPORT Process <0.1052.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", passwo...">>},...},...},...},...}
2020-12-10 13:20:44.417 [error] <0.1052.0> Cowboy stream 6 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.935.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", password...">>},...},...},...}
2020-12-10 13:22:08.316 [error] <0.1074.0> CRASH REPORT Process <0.1074.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", passwo...">>},...},...},...},...}
2020-12-10 13:22:08.316 [error] <0.1074.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1073.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", password...">>},...},...},...}
2020-12-10 13:22:30.977 [error] <0.1123.0> CRASH REPORT Process <0.1123.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", passwo...">>},...},...},...},...}
2020-12-10 13:22:30.979 [error] <0.1123.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1122.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", password...">>},...},...},...}
2020-12-10 13:23:10.071 [error] <0.1148.0> CRASH REPORT Process <0.1148.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", passwo...">>},...},...},...},...}
2020-12-10 13:23:10.071 [error] <0.1148.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1147.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", password...">>},...},...},...}
2020-12-10 15:28:23.945 [error] <0.1479.0> CRASH REPORT Process <0.1479.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", passwo...">>},...},...},...},...}
2020-12-10 15:28:23.951 [error] <0.1479.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1478.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", password...">>},...},...},...}
2020-12-10 15:29:39.245 [error] <0.1496.0> CRASH REPORT Process <0.1496.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", passwo...">>},...},...},...},...}
2020-12-10 15:29:39.250 [error] <0.1496.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.1495.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[host: \"localhost\", port: 5672, virtual_host: \"/\", username: \"user\", password...">>},...},...},...}
